config/sync/user.role.content_manager.yml
Editor  როლი 
`make drush cim `
=> #26 role editor

composer.json, composer.lock, config/sync/core.extension.yml, config/sync/system.action.user_add_role_action.manager.yml, config/sync/system.action.user_remove_role_action.manager.yml, config/sync/user.role.administrator.yml, config/sync/user.role.anonymous.yml, config/sync/user.role.authenticated.yml, config/sync/user.role.content_manager.yml, config/sync/user.role.manager.yml
როლს აქვს ყველა უფლება რაც Editor-ს და დამატებით მომხმარებლების მართვის და Editor როლის მინიჭების უფლება 
Editor როლის მინიჭების უფლებისთვის გამოვიყენე https://www.drupal.org/project/role_delegation ეს მოდული 
. `docker-compose exec php composer install`
. `make drush cim `
=> #27 role manager

composer.json, composer.lock, config/sync/block.block.bootstrap_account_menu.yml, config/sync/block.block.bootstrap_content.yml, config/sync/block.block.bootstrap_help.yml, config/sync/block.block.bootstrap_main_menu.yml, config/sync/block.block.bootstrap_page_title.yml, config/sync/block.block.bootstrap_tools.yml, config/sync/block.block.socialauthlogin.yml, config/sync/core.extension.yml, config/sync/social_auth.settings.yml, config/sync/social_auth_facebook.settings.yml, config/sync/system.action.user_add_role_action.manager.yml, config/sync/system.action.user_remove_role_action.manager.yml, config/sync/user.role.administrator.yml, config/sync/user.role.anonymous.yml, config/sync/user.role.authenticated.yml, config/sync/user.role.content_manager.yml, config/sync/user.role.manager.yml
დავაყენე social_auth მოდელი და კონტენტში გამოვაჩინე ბლოკი
=> 5 facebook social auth

composer.json, composer.lock
#38 ბაგის დაფიქსვის მიზნით `composer.json` ფაილში შევცვალე დრუპალის ქორის ვერსია ფიქსირებული `8.6.13`-დან `^8.6` ვერსიაზე. 
. `docker-compose exec php composer update drupal/core`
=> #38 change drupal version in composer.json

README.md, environments/services.develop.yml.dist, environments/settings.develop.php.dist, scripts/pre-install.sh, web/sites/default/services.yml, web/sites/default/settings.php
ამ PR-ში დალაგებულია ლოკალურად ინსტალაციის და დეველოპმენტ გარემოს პარამეტრების მოწესრიგების საკითხი.
ტესტირებისთვის:
1. სრულიად თავიდან დაკლონეთ პროექტი
2. გადადით `32-registration-deployment` ბრენჩზე
3. მიჰყევით ინსტალაციის ინსტრუქციას განახლებული `README.md` ფაილის მიხედვით
4. დასრულების შემდეგ, make sure, რომ არსებობს `web/sites/default/settings.php` ზოგადი, ხოლო `web/sites/default/settings.local.php` კონკრეტულად ლოკალის გარემოზე მორგებული ფაილი.
5. იგივე services.local.yml ფაილზე
6. დარწმუნდით რომ twig-ის დეველოპმენტ კონფიგურაციაა აქტიური, ანუ არ იკეშირებს და სორსში ტემპლეიტ ფაილებისთვის ვარიანტებს გვთავაზობს.  მაგალითად:
=> 32 registration deployment

config/sync/core.entity_form_display.user.user.default.yml, config/sync/core.entity_view_display.user.user.default.yml, config/sync/field.field.user.user.field_referral_url.yml, config/sync/field.storage.user.field_referral_url.yml, config/sync/views.view.referral_autocomplete.yml, web/modules/custom/girchi_referral/girchi_referral.module
* რეფერალურ მოდულში დაემატა `field_referral` ბმულის გენერატორი  და ახალი ველი `field_referral_url`.
*  წავშალე `მინდა ვიყო პოლიტიკოსი` ფილტრი.
*  `make drush cim`
=> 43 referral fix

README.md, composer.json, composer.lock, config/sync/core.extension.yml, config/sync/field.field.user.user.user_picture.yml, config/sync/language/en/field.field.user.user.user_picture.yml, config/sync/language/ka/views.view.user_admin_people.yml, custom-translations/en.po, custom-translations/ka.po, environments/settings.develop.php.dist
#21
გადავთარგმნე მომხმარებლის პროფილის და რეგისტრაციის ველები
ინსტალაცია:
Step 1 ) docker-compose exec php composer install
Step 2 ) make drush cim
Step 3 ) write this setting "$settings['custom_translations_directory'] = '../custom-translations';" to `girchi-com-d8/web/sites/default/settings.local.phpgirchi-com-d8/web/sites/default/settings.local.php` file
Step 4 ) make drush language-import
=> #21 Translated fields.

config/sync/user.role.manager.yml
შეიცვალა manager-ის permission და მიეცა უფლება რომ სხვა მომხმარებლებს მისცეს მენეჯერის როლი.
დაპულვის შემდეგ საჭიროა გაეშვას შემდეგი ბრძანება: 
**make drush cim**
=> #57 Give manager to give other users manager role.

Makefile, scripts/install.sh
- დავამატე `install` `Makefile` - ში, რომლის გამოყენებითაც ეშვება საინსტალაციო სკრიპტი
=> #54 Installation script

.env, Makefile, docker-compose.yml
#56 
დავამატე ახალი კონტეინერი (`girchi_ui_builder`) დაინსტალირებული `node`-თი, რომელზეც შემდგემში გაიბილდება [Girchi UI](https://github.com/Girchi/girchi-com-ui) პროექტი.
პროექტის გასაბილდად გამოიყენეთ `make build-ui` ბრძანება.
---
ეს არის #49 -ის პრერეკვიზიტული თასქი.
=> #56 UI-სთვის Docker კონტეინერის მომზადება

config/sync/core.extension.yml, config/sync/field.field.node.article.field_video_url.yml
=> #64 enabling facebook and vimeo embeds.

composer.json, composer.lock, config/sync/block.block.footer.yml, config/sync/block.block.mainnavigation.yml, config/sync/block.block.misionerismeniu.yml, config/sync/block.block.primaryadminactions.yml, config/sync/block.block.tabs.yml, config/sync/block.block.useraccountmenu.yml, config/sync/core.entity_form_display.user.user.register.yml, config/sync/core.entity_view_display.user.user.account_info_block.yml, config/sync/core.entity_view_display.user.user.compact.yml, config/sync/core.entity_view_display.user.user.compact_larger.yml, config/sync/core.entity_view_display.user.user.default.yml, config/sync/core.entity_view_display.user.user.user_header.yml, config/sync/core.extension.yml, config/sync/masquerade_float_block.settings.yml, config/sync/menu_export.export_data.yml, config/sync/menu_export.settings.yml, config/sync/system.menu.supporter-menu.yml, config/sync/user.role.missioner.yml, config/sync/views.view.supporter_registrants.yml, web/modules/custom/girchi_utils/templates/supporter_registration.html.twig, web/themes/custom/girchi/css/global.css, web/themes/custom/girchi/templates/forms/form--user-login-form.html.twig, web/themes/custom/girchi/templates/forms/form--user-register-form.html.twig, web/themes/custom/girchi/templates/header.htlm.twig, web/themes/custom/girchi/templates/menus/menu--supporter-menu.html.twig
#71 
- დავამატე მხარდამჭერების მიერ რეგისტრირებულთა სია რომელიც გაფილტრულია ამჟამად დალოგინებული მომხმარებლით(რეფერალ რეფერენსით);
- დავამატე "მისიონერების მენიუ" სადაც ჩანს მისიონერებისთვის საჭირო ლინკები;
- დავამატე "დარეგისტრირებულთა სიის" ღილაკი მისიონერების ფორმის ქვეშ;
- გავასწორე ვრაპერების პრობლემა მხარდამჭერების სიაზე;
- მარტივი სთაილინგით ცოტათი გავაუმჯობესე მომხმარებლის პროფაილის გვერდი რომ უფრო კითხვადი გამხდარიყო (ეს დროებითია, მომხმარებლის პროფაილის მარქაფის იმპლემენტაციამდე);
- დავამატე პირობა რომ მომხმარებელი თუ დალოგინებულია შესვლა/რეგისტრაციის ღილაკები აღარ უჩანდეს და ჩანდეს მხოლოდ გამოსვლის ღილაკი
=> 71 supporters

config/sync/chosen.settings.yml, config/sync/core.entity_form_display.node.article.default.yml, config/sync/core.entity_form_display.user.user.register.yml, config/sync/core.entity_view_display.user.user.account_info_block.yml, config/sync/core.entity_view_display.user.user.compact.yml, config/sync/core.entity_view_display.user.user.compact_larger.yml, config/sync/core.entity_view_display.user.user.user_header.yml, config/sync/field.storage.node.field_category.yml, config/sync/field.storage.node.field_tags.yml
=> #65 making categories and tags fields multi valued.

web/themes/custom/girchi/templates/forms/form--user-login-form.html.twig, web/themes/custom/girchi/templates/forms/form--user-register-form.html.twig
=> #77 Fix facebook login/register link

config/sync/core.entity_view_mode.taxonomy_term.teaser.yml, web/themes/custom/girchi/girchi.theme-suggestions.inc, web/themes/custom/girchi/templates/taxonomy/taxonomy-term--teaser.html.twig
- შეიქმნა teaser display mode taxonomy term-ისთვის
- გაკეთდა ტემპლეიტი 
`{% for item in content.field_tags['#items'] %}`
`  {{ print_entity('taxonomy_term', item.target_id , 'teaser' ) }}`
`{% endfor %}`
=> 83 taxonomy teaser display

config/sync/core.entity_view_display.node.article.teaser.yml, config/sync/image.style.article_teaser.yml, config/sync/taxonomy.vocabulary.news_categories.yml, config/sync/views.view.news.yml, web/themes/custom/girchi/templates/node/node--teaser.html.twig, web/themes/custom/girchi/templates/pager.html.twig, web/themes/custom/girchi/templates/views/views-view--news.html.twig, web/themes/custom/girchi/templates/views/views-view-unformatted--news.html.twig
- შეიქმნა teaser display mode-ი article კონტენტისთვის
- გადაკეთდა სიახლეების ლისტინგი
- გაისტილა სიახლეების ლისტინგი
- გაისტილა pager-ი
- view-ში შეიქმნა 2 ფილტრი , რომელიც url-იდან იღებს პარამეტრებს. 
მაგ: category=economy და tag=japaridze
=> #84 news listing

config/sync/editor.editor.basic_html.yml
Issue: #98 
დავამატე justify ღილაკი CKEditor-ში.
* `make drush cim`
=> #98 Add justify button in editor toolbar

config/sync/views.view.news.yml, web/modules/custom/girchi_utils/templates/top_videos.html.twig, web/themes/custom/girchi/templates/pager.html.twig
#119 
- გასწორდა ლინკი მთავარ გვერდზე
- შეიქმნა ფილტრი ვიუსთვის მარტო ვიდეოების გამოსტანად
=> #119 Fix video link and create filter for news view.

composer.json, composer.lock, config/sync/user.role.anonymous.yml, config/sync/user.role.authenticated.yml, web/sites/default/default.settings.php
=> #99 updating core version.

web/themes/custom/girchi/templates/blocks/block--system-menu-block--account.html.twig
#145 
მომხმარებლის მენიუს გავსტილე მარქაფის მხიედვით
*  დაბეჭდეთ  `User account menu ` ბლოკი (ID:`system_menu_block:account`) სასურველ გვერდზე.
*  მენიუს დასასამეტბლად შედით 
`http://girchi.docker.localhost/en/admin/structure/menu/manage/account/add`
=> #145 Style user menu block

web/themes/custom/girchi/templates/status-messages.html.twig
Issue: #115 
- დავაოვერაიდე `status-messages` თემფლეითი;
- მესიჯების გამოსატანად გამოვიყენე Bootstrap Alert კლასები;
=> Override system messages template.

web/modules/custom/girchi_utils/girchi_utils.module, web/modules/custom/girchi_utils/src/Plugin/Block/CategoryFilterBlock.php, web/modules/custom/girchi_utils/templates/categories-block.html.twig, web/themes/custom/girchi/girchi.theme, web/themes/custom/girchi/templates/nodes/node--teaser.html.twig, web/themes/custom/girchi/templates/taxonomy/taxonomy-term--teaser.html.twig
#141 
- Parent-ზე დაჭერით გადადის სიახლეების ჩამონათვალზე
- მენიუ ქვედონეზე ჩაიშლება მხოლოდ ისარზე დაჭერით
- აქტიური კატეგორია ჩაშილილი დარჩება სიახლეების ჩამონათვალზე გადასვლის შემდეგ
- teaser display-ის ლინკი გასწორდა.
=> #141 fix categories

web/themes/custom/girchi/templates/header.htlm.twig
#161 
დაიმალა პროგრეს ბარი html - დან
=> #161 hide progress bar

web/themes/custom/girchi/templates/forms/form--user-form.html.twig
=> Fix submit button.

config/sync/views.view.news.yml
#182 
* ჩავრთე **Aggregation**   და **Query settings** - ში მოვნიშნე `Distinct`
* `make` drush cim
=> #182 Remove dublicates from news view

config/sync/block.block.politicianblock.yml, config/sync/core.entity_form_display.user.user.register.yml, config/sync/core.entity_form_display.user.user.supporters_registration.yml, config/sync/core.entity_view_display.user.user.account_info_block.yml, config/sync/core.entity_view_display.user.user.compact.yml, config/sync/core.entity_view_display.user.user.compact_larger.yml, config/sync/core.entity_view_display.user.user.minimal.yml, config/sync/core.entity_view_display.user.user.user_header.yml
#173 
ბანერი გამოჩნდება მხოლოდ მომხმარებლის რედაქტირების გვერდზე
=> #173 display politician banner only on user edit page

web/themes/custom/girchi/girchi.theme, web/themes/custom/girchi/templates/header.htlm.twig
#170 
დალოგინებული მომხამრებლისთვის გამოვიტანე ინფორმაცია ჰედერში
=> #170 Add information about logged in user

web/themes/custom/girchi/girchi.theme, web/themes/custom/girchi/templates/nodes/node--article--full.html.twig
#190 
გამოვასწორე სიახლის შიდა გვერდზე კატეგორიის ლინკი
=> #190 fix category link bug in news page

composer.json, config/sync/language/en/page_manager.page.front_page.yml, config/sync/page_manager.page.front_page.yml
#185 
მთავარი გვერდი იყო შექმნილი ქართულად, ამიტომ თარგმნა შესაძლებელი იყო მხოლოდ ინგლისურ ენაზე. მომიწია პაჩის დაყენება.
გაუშვით ბრძანება `make drush cim`
=> 185 change front page title

web/themes/custom/girchi/templates/nodes/node--article--full.html.twig
კომენტარების და მსგავსი სიახლეების ბლოკებს გავუცვალე ადგილები
=> #199 Swap comment and related news blocks

config/sync/pathauto.pattern.article.yml
=> Add title in articles url. #208

composer.lock, config/sync/core.entity_view_display.node.office.teaser.yml, config/sync/core.extension.yml
#222 
დავაყენე D8 editor advanced link მოდული.
გაუშვით ბრძანება `make install`.
=> #222 Install D8 editor advanced link module.

web/modules/custom/girchi_utils/templates/lead-partners.html.twig, web/themes/custom/girchi/js/global.js, web/themes/custom/girchi/templates/footer.html.twig, web/themes/custom/girchi/templates/forms/form--user-login-form.html.twig, web/themes/custom/girchi/templates/forms/form--user-register-form.html.twig, web/themes/custom/girchi/templates/header.htlm.twig, web/themes/custom/girchi/templates/menus/menu--main.html.twig, web/themes/custom/girchi/templates/nodes/node--teaser.html.twig, web/themes/custom/girchi/templates/views/views-view--news.html.twig
#217 
გავასწორე #217 -ში მოცემული ბაგები
=> #217 Fix markup

web/modules/custom/girchi_utils/src/Plugin/Block/TagFilterBlock.php
#220 
გამოვასწორე თეგების ბლოკის ბაგი
=> #220 bug fixed in tag filter block

web/modules/custom/om_site_settings/src/Form/SiteSettingsForm.php, web/themes/custom/girchi/girchi.theme, web/themes/custom/girchi/templates/footer.html.twig
=> Add copyright text as setting field. #219

config/sync/om_site_settings.site_settings.yml, web/modules/custom/girchi_utils/src/Plugin/Block/CategoryFilterBlock.php, web/modules/custom/girchi_utils/src/Plugin/Block/FrontNewsBlock.php, web/modules/custom/girchi_utils/src/Plugin/Block/LeadPartner.php, web/modules/custom/girchi_utils/src/Plugin/Block/TagFilterBlock.php, web/modules/custom/girchi_utils/src/Plugin/Block/TopTopicsBlock.php, web/modules/custom/girchi_utils/src/Plugin/Block/TopVideosBlock.php, web/modules/custom/girchi_utils/src/Plugin/Block/UserProfile.php
=> 149 caching

config/sync/block.block.categoryfilterblockmobile.yml, web/modules/custom/girchi_utils/girchi_utils.module, web/modules/custom/girchi_utils/src/Plugin/Block/CategoryFilterBlockMobile.php, web/modules/custom/girchi_utils/templates/categories-block-mobile.html.twig, web/modules/custom/girchi_utils/templates/categories-block.html.twig, web/themes/custom/girchi/templates/nodes/node--article--full.html.twig, web/themes/custom/girchi/templates/views/views-view--news.html.twig, web/themes/custom/girchi/templates/views/views-view--search.html.twig
#207 
გავაკეთე responsive category filter Search, News და Article გვერდებზე
=> #207 bug fixed responsive categories block

web/modules/custom/girchi_utils/girchi_utils.module, web/modules/custom/girchi_utils/src/Plugin/Block/CategoryFilterBlock.php, web/modules/custom/girchi_utils/src/Plugin/Block/FrontNewsBlock.php, web/modules/custom/girchi_utils/src/Plugin/Block/LeadPartner.php, web/modules/custom/girchi_utils/src/Plugin/Block/TopTopicsBlock.php, web/modules/custom/girchi_utils/src/Plugin/Block/TopVideosBlock.php, web/modules/custom/girchi_utils/templates/front-page-articles.html.twig, web/modules/custom/girchi_utils/templates/top-videos.html.twig
=> Front page news blocks

web/modules/custom/girchi_utils/src/Plugin/Block/CategoryFilterBlock.php, web/themes/custom/girchi/js/global.js
#237  
გასწორდა კატეგორიების ბლოკი
=> 237 fix categories

config/sync/page_manager.page.front_page.yml, config/sync/system.site.yml, web/modules/custom/girchi_utils/src/Plugin/Block/FrontNewsBlock.php, web/modules/custom/girchi_utils/src/Plugin/Block/LeadPartner.php, web/modules/custom/girchi_utils/src/Plugin/Block/TopTopicsBlock.php, web/modules/custom/girchi_utils/src/Plugin/Block/TopVideosBlock.php, web/themes/custom/girchi/templates/header.htlm.twig
#232 
გავასწორე მომხარებლის აიკონი რესპნსივზე კონფიგურაციის მიხედვით
=> #232 Fix user icon for responsive design

web/modules/custom/girchi_utils/girchi_utils.module, web/themes/custom/girchi/templates/forms/form--user-login-form.html.twig
#239 
სეთინგების მიხედვით დაიმალება რეგისტრაციის და facebook-ით ავტორიზაციის ღილაკები
=> #239 Hide register and facebook auth buttons if checked in settings.

config/sync/core.entity_form_display.node.page.default.yml, config/sync/core.entity_form_display.paragraph.basic_text.default.yml, config/sync/core.entity_view_display.node.page.default.yml, config/sync/core.entity_view_display.paragraph.basic_text.default.yml, config/sync/field.field.node.page.field_is_about.yml, config/sync/field.field.paragraph.basic_text.field_subject_line.yml, config/sync/field.storage.node.field_is_about.yml, config/sync/field.storage.paragraph.field_subject_line.yml, config/sync/pathauto.pattern.basic_page.yml, web/modules/custom/girchi_utils/girchi_utils.module, web/themes/custom/girchi/templates/paragraphs/paragraph--basic-text.html.twig
#245 
- შეიცვალა field_title-ი field_subject_line-ით
- basic page-ს დაემატა boolean is_about
- გაკეთდა cusotm token-ი, რომელიც აგენერირებს path is_about-ის მიხედვით
=> 242 enhance about ux v2

composer.json, composer.lock, config/sync/core.entity_form_display.user.user.default.yml, config/sync/core.entity_view_display.user.user.default.yml, config/sync/core.extension.yml, config/sync/field.field.user.user.field_my_party_list.yml, config/sync/field.storage.user.field_my_party_list.yml
#253 #175 
დაყენდა Reference value pair მოდული და შეიქმნა იუზერისთვის შესაბამისი ველი.
`docker-compose exec php composer install`
=> #253 Update config.

config/sync/core.entity_view_display.node.page.page_header.yml, config/sync/core.entity_view_display.node.page.teaser.yml, config/sync/views.view.news.yml
დავამატე არტიკლების ფილტრი ნიუსების გვერდზე
=> #251 Add filter to news view

config/sync/core.extension.yml, config/sync/image.style.party_member.yml
#270 
გასწორდა bug-ი, რომლის გამოც არ ეშვებოდა `make drush cim` ბრძანება.
=> #270 Fix img style

config/sync/core.entity_form_display.user.user.default.yml, config/sync/core.entity_form_display.user.user.register.yml, config/sync/core.entity_form_display.user.user.supporters_registration.yml, config/sync/core.entity_view_display.user.user.account_info_block.yml, config/sync/core.entity_view_display.user.user.compact.yml, config/sync/core.entity_view_display.user.user.compact_larger.yml, config/sync/core.entity_view_display.user.user.default.yml, config/sync/core.entity_view_display.user.user.minimal.yml, config/sync/core.entity_view_display.user.user.user_header.yml, config/sync/field.field.user.user.field_rank.yml, config/sync/field.storage.user.field_rank.yml, web/modules/custom/girchi_utils/girchi_utils.module, web/modules/custom/girchi_utils/girchi_utils.services.yml, web/modules/custom/girchi_utils/src/GedRaitingService.php, web/modules/custom/girchi_utils/src/Plugin/Block/UserProfile.php, web/modules/custom/girchi_utils/templates/user_profile.html.twig
#263 
გავაკეთე რანკირების სია, რომელიც დაგენერირდება GeD-ების რაოდენობის მიხედვით.
გაუშვით ბრძამენა `make drush cim`.
=> 263 sidebar ged rating

web/modules/custom/girchi_utils/src/Plugin/Block/CategoryFilterBlock.php
#266 
შემოწმდა თუ არსებობს კატეგორია არტიკლის გვერდზე.
=> #266 Fix category block

config/sync/core.entity_form_display.paragraph.icon_items_grid.default.yml, config/sync/core.entity_view_display.paragraph.icon_items_grid.default.yml, config/sync/field.field.paragraph.icon_items_grid.field_icon_item.yml, config/sync/field.field.paragraph.icon_items_grid.field_style.yml, config/sync/field.storage.paragraph.field_icon_item.yml, config/sync/field.storage.paragraph.field_style.yml, config/sync/paragraphs.paragraphs_type.icon_items_grid.yml
#279 
შეიქმნა Icon items grid პარაგრაფი და Icom item პარაგრაფი
=> #279 Create Icon items grid paragraph

config/sync/core.entity_form_display.paragraph.timeline.default.yml, config/sync/core.entity_form_display.paragraph.timeline_item.default.yml, config/sync/core.entity_view_display.paragraph.timeline.default.yml, config/sync/core.entity_view_display.paragraph.timeline_item.default.yml, config/sync/field.field.paragraph.timeline.field_timeline_item.yml, config/sync/field.field.paragraph.timeline.field_title.yml, config/sync/field.field.paragraph.timeline_item.field_description.yml, config/sync/field.field.paragraph.timeline_item.field_title.yml, config/sync/field.storage.paragraph.field_timeline_item.yml, config/sync/paragraphs.paragraphs_type.timeline.yml, config/sync/paragraphs.paragraphs_type.timeline_item.yml
#280 
შეიქმნა Timeline paragraph და Timeline item paragraph-ი
=> #280 Create timeline paragraph

config/sync/field.field.node.promo_page.field_paragraphs.yml, config/sync/field.field.paragraph.icon_items_grid.field_icon_item.yml, config/sync/field.field.paragraph.school_process.field_paragraphs.yml
#288 
დაკონფიგურირდა პარაგრაფები
=> #288 Paragraph configuration update

web/themes/custom/girchi/js/global.js
##არწერა 
გავასწორე ჩამოშაშლელი მენიუ მობილურისთვის
=> #282 Fix dropdown for menu

web/themes/custom/girchi/girchi.theme
=> #291 Fix cache problem.

config/sync/field.field.user.user.field_referral.yml, web/modules/custom/girchi_utils/girchi_utils.module, web/themes/custom/girchi/girchi.theme, web/themes/custom/girchi/templates/forms/form--user-form.html.twig, web/themes/custom/girchi/templates/forms/form--user-register-form.html.twig, web/themes/custom/girchi/templates/header.htlm.twig
#302 #301 #300
ფოტოდან გაილინკა პროფილზე, რეფერალ ფილდი გახდა სავალდებულო და 
facebook-ით ავტორიზებულ ადამიანს გაუქრა პაროლის შეცვლის ველები
=> #302 Fix minor bugs

config/sync/image.style.logged_in_user_picture.yml, config/sync/image.style.user_sidebar.yml, web/modules/custom/girchi_utils/girchi_utils.module, web/modules/custom/girchi_utils/src/Plugin/Block/UserProfile.php, web/modules/custom/girchi_utils/templates/user_profile.html.twig, web/themes/custom/girchi/girchi.theme, web/themes/custom/girchi/templates/header.htlm.twig
##აღწერა
მომხარებლის ჰერედში და საიდბარზე შევქმენი სურათის სტილები შესაბამისი ზომებით.
ამ ტასკის ფარგლებში გავაკეთე #302 ტასკი
##ინსტალაცია 
* `make` drush cim
=> 63 avatar images

composer.json, composer.lock, config/sync/core.extension.yml, config/sync/mailsystem.settings.yml, config/sync/sendgrid_integration.settings.yml
#331 
დაყენდა sendgrid-ის მოდული
`docker-compose exec php composer install`
http://girchi.docker.localhost/ge/admin/config/services/sendgrid
აქ უნდა დაემატოს sendgrid-ის API KEY
=> #331 Install sendgrid_integration module and configure mail system

config/sync/core.entity_form_display.user.user.default.yml, config/sync/core.entity_view_display.user.user.default.yml, config/sync/field.field.user.user.field_political_ged.yml, config/sync/field.storage.user.field_political_ged.yml, config/sync/views.view.politician_support.yml, web/modules/custom/girchi_my_party_list/girchi_my_party_list.services.yml, web/modules/custom/girchi_my_party_list/src/PartyListCalculatorService.php, web/modules/custom/girchi_utils/src/GedRaitingService.php, web/themes/custom/girchi/templates/views/views-view-fields--party-list.html.twig
#344  #325 
გასწორდა მომხმარებლის ბლოკში ნუმერაცია და ვისაც ჯედი არ აქვს მიენიჭება სიაში ადგილი გვარის მიხედვით.
მთლიან პარტიულ სიაში პოლიტიკოსებს დაემატათ ველი, სადაც გამოჩნდება რამდენი ჯედი მიენიჭათ მომხმარებლების მიერ
შეიქმნა ცალკე view სადაც შეგვეძლება ნახვა კონკრეტული მომხმარებელი ვის რამდენი პროცენტით უჭერს მხარს
=> 344 fix user block

composer.json, composer.lock
#368 
Core-ის ვერსია 8.7-დან დავააფდეითე 8.7.5-ზე.
გაუშვით ბრძანება `docker-compose exec php composer install`.
=> Update core version

web/modules/custom/girchi_my_party_list/src/Controller/PartyListController.php, web/themes/custom/girchi/js/global.js, web/themes/custom/girchi/templates/views/views-view-fields--party-list.html.twig
გასწორდა ჩემი პარტიული სიის ajax call-ი
გასწორდა საერთო პარტიული სიის მობილური ვერსია.
=> 382 fix party list

config/sync/field.field.node.office.field_phone.yml, config/sync/field.field.user.user.field_referral.yml
#378 
კონტაქტის გვერდზე ტელეფონის ველი  და მომხმარებლის რეფერალის ველი გახდა ნებაყოფლობითი.
გაუშვით ბრძანება `make drush cim`, `make drush cr`.
=> Make phone and referral fields optional.

config/sync/views.view.news.yml
#421 
გასწორდა სიახლეების ფეიჯერი
=> #421 Fix news pager.

config/sync/views.view.news.yml
#423 
გასწორდა სიახლეების ფეიჯერი მობილურ ვერსიაზე.
=> #423 Fix news pager on mobile.

web/modules/custom/girchi_utils/templates/top-topics.html.twig
=> #417 Unfreeze donate block and link it.

web/modules/custom/girchi_my_party_list/src/PartyListCalculatorService.php
=> #413 Fix politician rating in party list.

web/modules/custom/girchi_donations/girchi_donations.module, web/modules/custom/girchi_donations/girchi_donations.routing.yml, web/modules/custom/girchi_donations/src/Controller/DonationsController.php
#409 
Url-ებიდან დღის დახურვა და ვალუტის კურსის აღება გადაიწერა
`hook_cron`-ში.
`make drus cr`
=> 409 payments day close

web/themes/custom/girchi/templates/nodes/node--article--full.html.twig
=> #426 Change article title element from h4 to h1.

web/modules/custom/girchi_donations/src/Controller/DonationsController.php, web/modules/custom/girchi_donations/src/Form/SingleDonationForm.php, web/themes/custom/girchi/css/custom.css, web/themes/custom/girchi/js/donation.js
* წინა მხარეს GeD ების ანგარიში მუშაობს tab ზე და აღარ ჩანს ველში ისრები
* აღარ იქეშება დონაციის ფორმა
* გაუმჯობესდა ანონიმური დონაცია
=> 431 donation issues

config/sync/field.field.node.article.field_meta_tags.yml, config/sync/field.storage.node.field_meta_tags.yml
#400 
არტიკლს დაემატა `field_meta_tags`.
გაუშვით ბრძანება `make drush cim`, `make drush cr`
=> #333 Add meta tags filed to article.

web/themes/custom/girchi/js/global.js, web/themes/custom/girchi/js/mypartylist.js, web/themes/custom/girchi/templates/pager.html.twig
#392 
გასწორდა პარტიულ სიაში ძებნა და ძებნის შემდეგ ფოკუსი ისევ რჩება input-ზე
`ბრაუზერის ქეშის გასუფთავება`
=> 392 party list search

web/themes/custom/girchi/js/global.js, web/themes/custom/girchi/templates/nodes/node--article--full.html.twig
#439 
- სიახლეების გვერდზე "ფავორიტი სიახლეები" გამოუჩნდება მხოლოდ დალოგინებულ მომხმარებელს.
- გავსტილე ჩექბოქსი
გაუშვით ბრძამება `make drush cr`.
=> #342 Improve favourite news checkbox.

composer.json, composer.lock, web/modules/custom/om_tbc_payments/cert/.cert.env.dist, web/modules/custom/om_tbc_payments/cert/.gitignore, web/modules/custom/om_tbc_payments/src/Services/PaymentService.php
გაკეთდა ლოკალური კონფიგურაცია სერტიფიკატის მისამართისა და პაროლისთვის.
დავაკოპიროთ `web/modules/custom/om_tbc_payments/cert/.cert.env.dist` ფაილი .cert.env  სახელით და შევავსოთ **CERT_PATH** და **CERT_PASS** შესაბამისი პარამეტრებით.
=> #410 Makepayment gateway configurable.

composer.json, patches/plug_and_pay_url.patch
**plugandpay** ბიბლიოთეკაში  მითითებული იყო მერჩანტის სხვა მისამართი, საჭირო გახდა გაპაჩვა.
=> Create patch for tbc plug and pay.

web/modules/custom/girchi_utils/girchi_utils.module, web/modules/custom/girchi_utils/src/Plugin/Block/PoliticianBlock.php, web/modules/custom/girchi_utils/templates/politician-block.html.twig
#468 
-  თუ მომხმარებელს მონიშნული აქვს "გახდი პოლიტიკოსი" მაშინ "მინდა პოლიტიკოსობა" ბლოკის მაგივრად ყველგან უნდა უჩანდეს "დააფინანსე პოლიტიკოსი".
`make drush cr`.
=> 468 right implementation of politician block

docker-compose.yml
შეიცვალა traefik-ის ვერსია 1.7-ზე
`docker-compose up -d`
=> #479 Change traefik version.

config/sync/views.view.ged_export.yml
#503 
შესაძლებელი გახდა მომხმარებლის მიერ გამომუშავებული(ფულით ნაყიდი და არაფულადი) GeD-ების გაექსპორტება ექსელის ფაილში, რომელიც დასორტირებულია კლებადობის მიხედვით.
`make drush cim` `make drush cr`.
view-ს სახელია `GeD export`.
=> #495 Add view for users ged export.

web/themes/custom/girchi/templates/views/views-view-fields--party-list.html.twig
#476 
`/2020-parliamentary-list`-ზე მობილურის ვერსიაზე შეიცვალა  GED-ის ფორმატი 
`make drush cr`.
=> #476 Change ged format.

web/themes/custom/girchi/girchi.theme, web/themes/custom/girchi/js/global.js
სკოლის გვერდზე გაიფიქსა ვიდეოს მოდალი და გამორთვისას ჩვეულებრივად პაუზდება.
`make drush cr` და გაწმინდეთ ბრაუზერის ქეში.
=> #527 Fix modal pause.

web/modules/custom/girchi_utils/templates/user_profile.html.twig, web/themes/custom/girchi/templates/blocks/block--system-menu-block--account.html.twig, web/themes/custom/girchi/templates/menus/menu--account.html.twig
პარტიულ სიაში დაიმალა user account sidebar menu დაულოგინებელი მომხმარებლებისთვის
=> hide sidebar account menu for anonymous users

web/modules/custom/girchi_donations/templates/girchi-donations-success.html.twig
#535 
რეგულარი დონაცეიების success page-ზე დაემატა ახალი ღილაკი "my regular donations".
:bell:  სტრინგის თარგმნა ვერ მოვახერხე და გასაკეთებელია 
=> #535 Add button on success page.

web/modules/custom/girchi_donations/templates/regular-donations.html.twig
რეგულარული დონაციების სამართავ view-ს დაემატა შემდეგი გადახდის თარიღის ველი.
=> #538 Add next payment date to donation.

web/modules/custom/girchi_donations/src/Controller/DonationsController.php, web/modules/custom/girchi_donations/src/Plugin/QueueWorker/RegularDonationProcessor.php
#543 
`make drush cr` 
დონაციის გაკეთების შემდეგ `ged transactions`-ში შეამოწმე, რომ ტრანზაქციის ტიპი იყოს `0026 - ფულადი კონტრიბუცია`.
=> Add transaction type for donation transactions.

web/themes/custom/girchi/templates/nodes/node--article--full.html.twig
=> #493 Improve article full page.

web/themes/custom/girchi/templates/forms/form--user-form.html.twig
#521 
გასწორდა პროფილის ფოტოს ღილაკი.
=> #521 Fix user profile picture button.

config/sync/core.entity_form_display.donation.donation.default.yml, config/sync/core.entity_view_display.donation.donation.default.yml, config/sync/field.field.donation.donation.field_ged_transaction.yml, config/sync/field.storage.donation.field_ged_transaction.yml, config/sync/views.view.donations.yml, web/modules/custom/girchi_donations/composer.json, web/modules/custom/girchi_donations/drush.services.yml, web/modules/custom/girchi_donations/src/Commands/GirchiDonationsCommands.php, web/modules/custom/girchi_donations/src/Controller/DonationsController.php
გავაკეთე `drush`-ის კომანდი რელაციების გასაფიქსად
* ფროდაქშნის ბაზის შეიმპორტება
* `make` drush cim
* `make` drush girchi_donations:fix-relation
donation view -ში შეიძლება შედეგის შემოწმება
:exclamation: რელაცისი გარეშე რჩება 4ცალი  ლარიანი დონაცია რომელიც დონაციების გაშევებისას გაკეთდა და სესიის დაკარგვის გამო ვერ შეიქმნა
=> 500 transaction relation

web/themes/custom/girchi/girchi.libraries.yml
Change donation lib version to 1.1
=> Change donation.js lib version.

web/modules/custom/girchi_donations/src/Controller/DonationsController.php
Fix regular donation taxonomy term id.
=> Change taxonomy id for regular donation.

web/themes/custom/girchi/templates/footer.html.twig
#548 
footer-ში დაემატა ინსტაგრამის icon-ი.
`make update-ui` 
გაწმინდეთ ბრაუზერის ქეში და site setting-ში გაუწერეთ ინსტაგრამის url.
=> #548 Add instagram icon.

web/modules/custom/girchi_my_party_list/templates/politician-rating-block.html.twig
რომელიმე ტოპ პოლიტიკოსს წაუშალეთ ფოტო და გატესტეთ, რომ ავატარი მიყვებოდეს.
`make drush cr`.
=> Fix image bug.

web/modules/custom/girchi_my_party_list/templates/politician-rating-block.html.twig
#571 
მობილურის ვერსიაზე გასწორდა ged-ის ფორმატირება
`make drush cr`.
=> Fix ged format.

web/modules/custom/girchi_ged_transactions/girchi_ged_transactions.module, web/themes/custom/girchi/girchi.theme
#509
პროგრეს ბარის კონფიგი ამოვიღე site settings-დან და დავაკომფიგურირე keyValueStore-ით.
`make drush cr` და გაუშვით კრონი.
=> #509 fix progress bar config.

config/sync/google_tag.container.girchi.yml, config/sync/google_tag.settings.yml
=> #489 Configure GoogleTagManager module.

config/sync/page_manager.page_variant.front_page-panels_variant-0.yml, web/modules/custom/girchi_my_party_list/templates/politician-rating-block.html.twig
შეიცვალა პოლიტიკოსების რეიტინგის ბლოკის ადგილმდებარეობა
`make drush cim` 
=> #578 Change politican rating block place.

config/sync/views.view.regular_donations.yml
#582 
რეგულარულ დონაციას დაემატა პერიოდით გაფილტვრა.
`make drush cim`, `make drush cr`
=> Add filter to regular donation view.

web/modules/custom/girchi_utils/girchi_utils.module
hook_presave გადაკეთდა hook_update-ად girchi_utils მოდულში
=> Change user_presave hook to user_update in utils module.

web/modules/custom/girchi_referral/templates/top-referrals.html.twig
#626 
ტოპ რეფერალების ბლოკში შეიცვალა ლარის ფორმატი და გამოდის დამრგვარებულად
=> Change gel format.

config/sync/views.view.ged_transaction.yml, config/sync/views.view.referral_autocomplete.yml, config/sync/views.view.referral_transaction.yml, web/modules/custom/girchi_my_party_list/src/PartyListCalculatorService.php, web/modules/custom/girchi_referral/src/GetUserReferralsService.php, web/modules/custom/girchi_referral/src/Plugin/Block/TopReferrals.php
#586 
ის მომხმარებლები, რომლებსაც სახელი და გვარი არ უწერიათ, გაქრნენ ყველა საჯარო აქტივობიდან.
`make drush cim`, `make drush cr`
- ტოპ რეფერალები (სრული სიით) (front page)
- `/2020-parliamentary-list` მხარდამჭერების მოდალი.
- მომხმარებლის public profile (მხარდამჭერების მოდალი)
- `/ged-transactions`
- `/user/referral-transaction` (საბოს ყავდა ერთი უსახელო მხარდამჭერი და მაგის მაგალითზე  გატესტეთ)
=> უსახელო მომხმარებლების გაქრობა

.gitignore, config/sync/field.field.donation.donation.field_source.yml, config/sync/field.storage.donation.field_source.yml, config/sync/views.view.donations.yml, web/modules/custom/girchi_donations/girchi_donations.services.yml, web/modules/custom/girchi_donations/src/Form/SingleDonationForm.php, web/modules/custom/girchi_donations/src/Plugin/QueueWorker/RegularDonationProcessor.php, web/modules/custom/girchi_donations/src/Utils/CreateGedTransaction.php, web/modules/custom/girchi_paypal/composer.json, web/modules/custom/girchi_paypal/config/install/girchi_paypal.paypalsettings.yml, web/modules/custom/girchi_paypal/credentials/.credentials.env.dist, web/modules/custom/girchi_paypal/credentials/.gitignore, web/modules/custom/girchi_paypal/drush.services.yml, web/modules/custom/girchi_paypal/girchi_paypal.links.menu.yml, web/modules/custom/girchi_paypal/girchi_paypal.module, web/modules/custom/girchi_paypal/girchi_paypal.routing.yml, web/modules/custom/girchi_paypal/girchi_paypal.services.yml, web/modules/custom/girchi_paypal/src/Commands/GirchiPaypalCommands.php, web/modules/custom/girchi_paypal/src/Controller/PaypalController.php, web/modules/custom/girchi_paypal/src/Form/PaypalSettingsForm.php, web/modules/custom/girchi_paypal/src/Utils/PayPalClient.php, web/modules/custom/girchi_paypal/src/Utils/PaypalUtils.php, web/themes/custom/girchi/css/custom.css, web/themes/custom/girchi/js/paypal.js
- დონაციას დაემატა წყაროს ველი (field_source) 
- შეიქმნა დრაშის კომანდი რომელიც ყველა ძველ დონაციას დაუსეტავს source-ს **tbc**
`set-donation-source`
- დაემატა სპინერი დონაციის გვერდს
- დაემატა ვალიდაცია, რომელიც არარსებული პოლიტიკოსის ან მიზანის შემთხვევაში დონაციას INVALID სტატუს დაუსეტავს და მომხმარებელს ჯედს არ ჩაურიცხავს
- Paypal-ის credentials გავიდა მოდულის კონფიგურაციაში `admin/config/girchi_paypal/paypalsettings`
- ლოგირება გაუმჯობესდა
- `drush cim`
- გავუშვათ `set-donation-source` კომანდი
`admin/config/girchi_paypal/paypalsettings` ფორმა უნდა შევავსოთ შესაბამისი Paypal-ის credential-ებით 
- `drush cr`
=> 628 improve paypal

web/modules/custom/girchi_donations/girchi_donations.module, web/modules/custom/girchi_donations/src/Controller/DonationsController.php, web/modules/custom/girchi_donations/templates/girchi-donations.html.twig
Paypal-ის გადახდა ჩაირთო ყველა მომხმარებლისთვის
=> #633 Activate paypal publicly.

config/sync/views.view.party_list.yml, web/modules/custom/girchi_my_party_list/girchi_my_party_list.services.yml, web/modules/custom/girchi_my_party_list/src/PartyListCalculatorService.php, web/modules/custom/girchi_utils/girchi_utils.module
:warning: ამ PRის დამეჯრვამდე უნდა დაიმერჯოს #610 :warning:
გადაიწერა პარტიული სიის კალკულატორი
გაუშვით კრონი
=> Hot fix/party list calculator

web/themes/custom/girchi/js/global.js
#518 
https://github.com/Girchi/girchi-com-ui/pull/131
- `make` update-ui
- `make` drush cr
ჩართეთ JS აგრეგაცია და შეამოწმეთ ერორები კონსოლში და ჯავასკრიპტის ფუნქციონალი
=> Fixup for drupal js aggregation.

web/modules/custom/girchi_leaderboard/src/Form/LeaderboardForm.php, web/modules/custom/girchi_referral/girchi_referral.services.yml, web/modules/custom/girchi_referral/src/EventSubscriber/DonationSubscriber.php
#651 
თუ მომხმარებელი დააფინანსებს იმ პოლიტიკოსს, რომელიც მას რეფერალებში ჰყავს მონიშნული, ამ პოლიტიკოსს რეფერალების 10% აღარ ჩაერიცხება
=> change referral logic.

web/modules/custom/girchi_my_party_list/girchi_my_party_list.routing.yml, web/modules/custom/girchi_my_party_list/src/Controller/PartyListController.php, web/modules/custom/girchi_my_party_list/templates/girchi-my-party-list.html.twig, web/modules/custom/girchi_utils/girchi_utils.module, web/themes/custom/girchi/js/mypartylist.js
#589 
ამ თასქის დამერჯვამდე უნდა დაიმერჯოს `https://github.com/Girchi/girchi-com-ui/pull/133`. 
`make build-ui`
გაწმინდეთ ბრაუზერის ქეში.
=> 589 fix my party list

web/modules/custom/girchi_leaderboard/templates/lead-partners.html.twig
=> add margin to lead partners block.

web/themes/custom/girchi/templates/pages/girchi-main.html.twig
=> Delete container from main page.

config/sync/menu_export.export_data.yml, config/sync/menu_export.settings.yml, web/themes/custom/girchi/girchi.theme
=> 640 add menu

web/modules/custom/girchi_utils/girchi_utils.module
#664 
ანონიმური მომხმარებლისთვის გასწორდა ged-ის ქეში
=> #664 Fix ged value caching for anonymous user.

web/themes/custom/girchi/js/donation.js, web/themes/custom/girchi/templates/header.htlm.twig
პოლიტიკოსის საჯარო პროფილიდან დაფინანსებაზე გადასცლისას ველში არ ისეტებოდა ქვერი სტრინგის value.
გაწმინდეთ ბრაუზერის ქეში
=> Donation hot fix

config/sync/views.view.users.yml
=> Show only public users in view.

config/sync/core.extension.yml, config/sync/girchi_supporters_register_form.registersupporter.yml, web/modules/custom/girchi_supporters_register_form/config/install/girchi_supporters_register_form.registersupporter.yml, web/modules/custom/girchi_supporters_register_form/girchi_supporters_register_form.info.yml, web/modules/custom/girchi_supporters_register_form/girchi_supporters_register_form.module, web/modules/custom/girchi_supporters_register_form/girchi_supporters_register_form.routing.yml, web/modules/custom/girchi_supporters_register_form/src/Form/RegisterSupporterForm.php, web/modules/custom/girchi_supporters_register_form/templates/girchi-supporters-register-form.html.twig, web/modules/custom/girchi_users/girchi_users.services.yml, web/modules/custom/girchi_users/src/UserBadgesChangeDetectionService.php, web/modules/custom/girchi_users/src/UsersUtils.php, web/themes/custom/girchi/templates/pages/page--rs.html.twig
#706 
1. დაემატა ახალი გვერდი /rs
2. ამ გვერდის გახსნა შეუძლიათ მხოლოდ missioner როლის მომხმარებლებს
3. გვერდზე არის მარტივი ფორმა მომხმარებლის სწრაფად დასარეგისტრირებლად
4. ახალი მომხმარებლის შექმნისას, მისი რეფერალი ავტომატურად ხდება ის იუზერი, რომელიც რეგისტრატორს ჰყავს მითითებული რეფერალად (აზრი არის რომ ეს რეგისტრატორი, იმის თიმის წევრია)
4. ვალიდაცია ხდება პირადი ნომრის, ელფოსტის და ტელეფონის ნომრების უნიკალურობაზე (ამისთვის girchi_users მოდულში დაემატა ახალი სერვისი UsersUtils)
5. UserBadgesChangeDetectionService ამ სერვისში იყო პატარა პრობლემა მომხმარებლის შექმნის დროს და გავფიქსე
6. State API-ის გამოყენებით, ინახება რეგისტრატორის ჯამური რეგისტრაციები.
=> 706 fast register form

web/modules/custom/girchi_donations/src/Plugin/QueueWorker/RegularDonationProcessor.php, web/modules/custom/girchi_ged_transactions/src/Commands/GirchiGedTransactionsCommands.php
##
`make drush fix-reg-transaction-type`
=> Fix donation type.

config/sync/field.field.user.user.field_last_name.yml, web/modules/custom/girchi_referral/src/Plugin/Block/TopReferrals.php
=> Hot fix/hide unnamed user referrals

web/modules/custom/girchi_users/src/Commands/GirchiUsersCommands.php, web/modules/custom/girchi_users/src/Plugin/QueueWorker/SpecialTransactionsQueue.php
`special-transactions`
`test-special-transactions`
=> Fix special transactions.

config/sync/editor.editor.basic_html.yml, config/sync/editor.editor.user_info.yml, config/sync/filter.format.user_info.yml, config/sync/user.role.authenticated.yml
#709 
მომხმარებლის საჯარო პროფილისთვის (ინტრო, ბიო) დაემატა ახალი ტექსტ ედიტორი, შეზღუდული უფლებებით.
(ლისტებზე არ შევზღუდე, იყენებენ )
=> Create new text format for authenticated users

config/sync/system.maintenance.yml, web/themes/custom/girchi/templates/pages/maintenance-page.html.twig
=> Create template for maintenance page.

web/modules/custom/girchi_supporters_register_form/src/Form/RegisterSupporterForm.php
@IliaNoz @glontianano ძალიან პატარა ცვლილებაა. რეფერალის ლოგიკას ვცვლი უბრალოდ.
=> Remove 'team' thing from logic. refs #706

web/modules/custom/girchi_donations/girchi_donations.module, web/modules/custom/girchi_donations/src/Commands/GirchiDonationsCommands.php
ტაქსონომიის წაშლის შემდეგ, ისეთ რეგულარულ დონაციებს რომლებსაც მითითებული ქონდათ არსებული ტაქსონომია
ყველას დაესეტება მიზანში "გირჩი".
ასევე გაკეთდა ქომანდი რომელიც არსებულ რეგულარულ დონაცებს, რომლებსაც წაშლილი აქვთ მიზანი დაუსეტავს "გირჩი".
=> Reg donations aim fix

web/modules/custom/girchi_supporters_register_form/config/install/girchi_supporters_register_form.usersreport.yml, web/modules/custom/girchi_supporters_register_form/girchi_supporters_register_form.links.menu.yml, web/modules/custom/girchi_supporters_register_form/girchi_supporters_register_form.routing.yml, web/modules/custom/girchi_supporters_register_form/src/Form/UsersReportForm.php
=> Create custom report for new registrations.

config/sync/user.role.content_manager.yml, config/sync/user.role.financial_manager.yml, config/sync/user.role.manager.yml, config/sync/user.role.social_analytics_manager.yml
არავტორიზებული და authenticated მომხამრებლის გარდა ყველა სხვა როლს დაურბუნდა ckeditorის მთლიანი ფუნქციონალი
=> ckeditorის უფლებების შეცვლა

web/modules/custom/girchi_ged_transactions/girchi_ged_transactions.module, web/modules/custom/girchi_ged_transactions/girchi_ged_transactions.services.yml, web/modules/custom/girchi_ged_transactions/src/SummaryGedCalculationService.php, web/modules/custom/girchi_utils/girchi_utils.module, web/modules/custom/girchi_utils/girchi_utils.services.yml, web/modules/custom/girchi_utils/src/GedRaitingService.php, web/modules/custom/girchi_utils/src/Plugin/Block/UserProfile.php
- შეამოწმეთ, რომ მომხმარებელს edit pageზე rank rating სწორად აქვს მინიჭებული.
- მიანიჭეთ ვინმეს ჯედები და დარწმუნდით, რომ კრონის გაშვებაზე პროგრეს ბარი იცვლება.
=> Improve rank rating

web/modules/custom/girchi_my_party_list/composer.json, web/modules/custom/girchi_my_party_list/drush.services.yml, web/modules/custom/girchi_my_party_list/src/Commands/GirchiMyPartyListCommands.php
=> Create command to delete non politicians from party list.

web/modules/custom/girchi_donations/girchi_donations.module, web/modules/custom/girchi_donations/src/Commands/GirchiDonationsCommands.php, web/modules/custom/girchi_referral/girchi_referral.services.yml, web/modules/custom/girchi_referral/src/EventSubscriber/DonationSubscriber.php, web/modules/custom/girchi_users/girchi_users.module
#784 
- თუ მომხმარებელი პოლიტიკოსი აღარაა და მას ვინმე აფინანსებს, ასეთ რეგ. დონაციებს უნდა შეეცვალოთ მიზანი
- თუ მომხმარებელი წაიშალა,მაგრამ მას ვინმე აფინანსებს რეგ. დონაციით, ასეთი რეგულარული დონაციისთვის უნდა შეიცვალოს მიზანი.
- მომხმარებლის წაშლის შემდგომ, უნდა დაპაუზდეს მისი აქტიური რეგულარული დონაციები
- თუ მომხმარებელი წაიშალა, მაგრამ ვინმეს რეფერალებში ყავდა მონიშნული, ასეთი რეფერალის ველი უნდა გასუფთავდეს
- გატესტეთ, რომ მუშაობს ანონიმური დონაცია
- რეგულარული დონაციის დროს, უნდა შემოწმდეს, რომ იუზერი არსებობს და მხოლოდ ამის შემდეგ უნდა ჩაიყაროს ქიუში
- გაუშვით ბრძანება `drush delete-aim` (შლის aim_idს თუ პოლიტიკოსის დაფინანსებაა)
- - გაუშვით ბრძანება `drush change-donation-type` (შლის პოლიტიკოსს და უსეტავს aim_id-ს თუ მომხმარებელი პოლიტიკოსი აღარაა)
=> 784 regular donations bug fix

web/modules/custom/girchi_donations/girchi_donations.module, web/modules/custom/girchi_donations/src/Controller/DonationsController.php, web/modules/custom/girchi_donations/templates/girchi-donations.html.twig, web/themes/custom/girchi/js/donation.js
Disable anonymous transactions feature, from now on users will be asked to login if they are not already logged in.
=> Adding default project selector via URL query string.
